begin;
create table if not exists public.loyalty_accounts(id uuid primary key default gen_random_uuid(),user_id uuid not null unique references auth.users(id) on delete cascade,available_points bigint not null default 0 check(available_points>=0),pending_points bigint not null default 0 check(pending_points>=0),lifetime_earned bigint not null default 0 check(lifetime_earned>=0),lifetime_redeemed bigint not null default 0 check(lifetime_redeemed>=0),created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now()));
create table if not exists public.reward_rules(id uuid primary key default gen_random_uuid(),name text not null,rule_type text not null check(rule_type in('purchase','first_order','birthday','category','brand','campaign')),points_per_try numeric(12,4) not null default 0 check(points_per_try>=0),bonus_points bigint not null default 0 check(bonus_points>=0),redemption_value_per_point numeric(12,4) not null default .01 check(redemption_value_per_point>0),minimum_order_amount numeric(12,2) not null default 0 check(minimum_order_amount>=0),maximum_redeemable_points bigint,category_id uuid references public.categories(id) on delete set null,brand_id uuid references public.brands(id) on delete set null,campaign_id uuid references public.campaigns(id) on delete set null,priority integer not null default 100,is_active boolean not null default true,starts_at timestamptz,ends_at timestamptz,created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now()));
create table if not exists public.loyalty_transactions(id uuid primary key default gen_random_uuid(),account_id uuid not null references public.loyalty_accounts(id) on delete restrict,user_id uuid not null references auth.users(id) on delete restrict,order_id uuid references public.orders(id) on delete set null,type text not null check(type in('earn','redeem','refund','adjustment','bonus','manual_add','manual_remove')),points bigint not null check(points<>0),balance_after bigint not null check(balance_after>=0),status text not null default 'completed' check(status in('pending','completed','cancelled')),description text,metadata jsonb not null default '{}'::jsonb,idempotency_key text unique,created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now()));
create table if not exists public.reward_redemptions(id uuid primary key default gen_random_uuid(),account_id uuid not null references public.loyalty_accounts(id) on delete restrict,user_id uuid not null references auth.users(id) on delete restrict,order_id uuid not null references public.orders(id) on delete restrict,points bigint not null check(points>0),discount_amount numeric(12,2) not null check(discount_amount>=0),status text not null default 'redeemed' check(status in('reserved','redeemed','refunded','cancelled')),created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now()),unique(order_id));
alter table public.orders add column if not exists loyalty_points_earned bigint not null default 0,add column if not exists loyalty_points_redeemed bigint not null default 0,add column if not exists loyalty_discount numeric(12,2) not null default 0,add column if not exists loyalty_snapshot jsonb not null default '{}'::jsonb;
create index if not exists loyalty_transactions_user_created_idx on public.loyalty_transactions(user_id,created_at desc);create index if not exists loyalty_transactions_order_idx on public.loyalty_transactions(order_id);create index if not exists reward_rules_active_type_idx on public.reward_rules(is_active,rule_type,priority);create index if not exists reward_redemptions_user_created_idx on public.reward_redemptions(user_id,created_at desc);
alter table public.loyalty_accounts enable row level security;alter table public.loyalty_transactions enable row level security;alter table public.reward_rules enable row level security;alter table public.reward_redemptions enable row level security;
create policy loyalty_account_owner_admin_read on public.loyalty_accounts for select using(user_id=auth.uid() or public.current_user_is_admin());create policy loyalty_transactions_owner_admin_read on public.loyalty_transactions for select using(user_id=auth.uid() or public.current_user_is_admin());create policy reward_rules_authenticated_read on public.reward_rules for select using(auth.uid() is not null and (is_active or public.current_user_is_admin()));create policy reward_redemptions_owner_admin_read on public.reward_redemptions for select using(user_id=auth.uid() or public.current_user_is_admin());
revoke insert,update,delete on public.loyalty_accounts,public.loyalty_transactions,public.reward_rules,public.reward_redemptions from anon,authenticated;
insert into public.reward_rules(name,rule_type,points_per_try,redemption_value_per_point,minimum_order_amount,priority) select 'Standart alışveriş puanı','purchase',1,.01,1,100 where not exists(select 1 from public.reward_rules where rule_type='purchase');
create or replace function public.ensure_loyalty_account(p_user uuid) returns uuid language plpgsql security definer set search_path='' as $$declare v_id uuid;begin insert into public.loyalty_accounts(user_id)values(p_user)on conflict(user_id)do update set updated_at=public.loyalty_accounts.updated_at returning id into v_id;return v_id;end$$;
create or replace function public.earn_loyalty_points(p_user_id uuid,p_order_id uuid,p_points bigint default null,p_reason text default 'Sipariş kazanımı')returns bigint language plpgsql security definer set search_path='' as $$declare v_account uuid;v_points bigint;v_balance bigint;v_total numeric;begin if not public.current_user_is_admin() and auth.uid()<>p_user_id then raise exception'forbidden';end if;select grand_total into v_total from public.orders where id=p_order_id and user_id=p_user_id for update;if not found then raise exception'order_not_found';end if;select coalesce(p_points,floor(v_total*r.points_per_try)::bigint)into v_points from public.reward_rules r where r.rule_type='purchase'and r.is_active and v_total>=r.minimum_order_amount and (r.starts_at is null or r.starts_at<=now())and(r.ends_at is null or r.ends_at>=now())order by r.priority limit 1;v_points:=coalesce(v_points,0);if v_points<=0 then return 0;end if;v_account:=public.ensure_loyalty_account(p_user_id);update public.loyalty_accounts set available_points=available_points+v_points,lifetime_earned=lifetime_earned+v_points,updated_at=now()where id=v_account returning available_points into v_balance;insert into public.loyalty_transactions(account_id,user_id,order_id,type,points,balance_after,description,idempotency_key)values(v_account,p_user_id,p_order_id,'earn',v_points,v_balance,p_reason,'earn:'||p_order_id)on conflict(idempotency_key)do nothing;update public.orders set loyalty_points_earned=v_points,loyalty_snapshot=loyalty_snapshot||jsonb_build_object('earned',v_points)where id=p_order_id;perform public.publish_notification_event('points_earned','order',p_order_id::text,jsonb_build_object('user_id',p_user_id,'points',v_points));insert into public.analytics_events(event_name,entity_type,entity_id,user_id,payload)values('points_earned','order',p_order_id::text,p_user_id,jsonb_build_object('points',v_points));insert into public.customer_activity(customer_id,activity_type,description,metadata)select id,'loyalty_points_earned','Sadakat puanı kazanıldı',jsonb_build_object('points',v_points,'order_id',p_order_id)from public.customer_profiles where user_id=p_user_id;return v_points;exception when unique_violation then return 0;end$$;
create or replace function public.redeem_loyalty_points(p_points bigint,p_order_id uuid)returns numeric language plpgsql security definer set search_path='' as $$declare v_user uuid:=auth.uid();v_account public.loyalty_accounts%rowtype;v_max bigint;v_value numeric;v_discount numeric;v_total numeric;begin if v_user is null or p_points<=0 then raise exception'invalid_points';end if;select*into v_account from public.loyalty_accounts where user_id=v_user for update;if not found or v_account.available_points<p_points then raise exception'insufficient_points';end if;select grand_total into v_total from public.orders where id=p_order_id and user_id=v_user for update;if not found then raise exception'order_not_found';end if;select maximum_redeemable_points,redemption_value_per_point into v_max,v_value from public.reward_rules where rule_type='purchase'and is_active order by priority limit 1;if v_max is not null and p_points>v_max then raise exception'points_limit';end if;v_discount:=least(v_total,round(p_points*coalesce(v_value,.01),2));update public.loyalty_accounts set available_points=available_points-p_points,lifetime_redeemed=lifetime_redeemed+p_points,updated_at=now()where id=v_account.id;insert into public.loyalty_transactions(account_id,user_id,order_id,type,points,balance_after,description,idempotency_key)values(v_account.id,v_user,p_order_id,'redeem',-p_points,v_account.available_points-p_points,'Siparişte puan kullanımı','redeem:'||p_order_id);insert into public.reward_redemptions(account_id,user_id,order_id,points,discount_amount)values(v_account.id,v_user,p_order_id,p_points,v_discount);update public.orders set loyalty_points_redeemed=p_points,loyalty_discount=v_discount,discount_total=discount_total+v_discount,grand_total=greatest(0,grand_total-v_discount),loyalty_snapshot=jsonb_build_object('points',p_points,'discount',v_discount,'value_per_point',v_value)where id=p_order_id;perform public.publish_notification_event('points_used','order',p_order_id::text,jsonb_build_object('user_id',v_user,'points',p_points));insert into public.analytics_events(event_name,entity_type,entity_id,user_id,payload)values('points_used','order',p_order_id::text,v_user,jsonb_build_object('points',p_points,'discount',v_discount)),('reward_conversion','order',p_order_id::text,v_user,jsonb_build_object('points',p_points));perform public.write_audit_log('loyalty_points_used','order',p_order_id::text,'Loyalty redemption',null,jsonb_build_object('points',p_points,'discount',v_discount),'{}');return v_discount;end$$;
create or replace function public.refund_loyalty_points(p_order_id uuid)returns boolean language plpgsql security definer set search_path='' as $$declare v_r public.reward_redemptions%rowtype;v_balance bigint;begin if not public.current_user_is_admin() then raise exception'forbidden';end if;select*into v_r from public.reward_redemptions where order_id=p_order_id and status='redeemed'for update;if found then update public.loyalty_accounts set available_points=available_points+v_r.points,lifetime_redeemed=greatest(0,lifetime_redeemed-v_r.points),updated_at=now()where id=v_r.account_id returning available_points into v_balance;update public.reward_redemptions set status='refunded',updated_at=now()where id=v_r.id;insert into public.loyalty_transactions(account_id,user_id,order_id,type,points,balance_after,description,idempotency_key)values(v_r.account_id,v_r.user_id,p_order_id,'refund',v_r.points,v_balance,'İptal/iade puan geri yüklemesi','refund:'||p_order_id)on conflict do nothing;end if;return true;end$$;
create or replace function public.adjust_loyalty_points(p_user_id uuid,p_points bigint,p_reason text)returns bigint language plpgsql security definer set search_path='' as $$declare v_account uuid;v_balance bigint;begin if not public.current_user_is_admin()or p_points=0 then raise exception'forbidden';end if;v_account:=public.ensure_loyalty_account(p_user_id);update public.loyalty_accounts set available_points=available_points+p_points,lifetime_earned=lifetime_earned+greatest(p_points,0),updated_at=now()where id=v_account and available_points+p_points>=0 returning available_points into v_balance;if not found then raise exception'insufficient_points';end if;insert into public.loyalty_transactions(account_id,user_id,type,points,balance_after,description)values(v_account,p_user_id,case when p_points>0 then'manual_add'else'manual_remove'end,p_points,v_balance,p_reason);perform public.write_audit_log('loyalty_points_adjusted','user',p_user_id::text,'Loyalty account',null,jsonb_build_object('points',p_points,'balance',v_balance),jsonb_build_object('reason',p_reason));return v_balance;end$$;
create or replace function public.admin_save_reward_rule(p_rule jsonb)returns uuid language plpgsql security definer set search_path='' as $$declare v_id uuid;begin if not public.current_user_is_admin()then raise exception'forbidden';end if;v_id:=nullif(p_rule->>'id','')::uuid;insert into public.reward_rules(id,name,rule_type,points_per_try,bonus_points,redemption_value_per_point,minimum_order_amount,maximum_redeemable_points,priority,is_active)values(coalesce(v_id,gen_random_uuid()),p_rule->>'name',p_rule->>'rule_type',coalesce((p_rule->>'points_per_try')::numeric,0),coalesce((p_rule->>'bonus_points')::bigint,0),coalesce((p_rule->>'redemption_value_per_point')::numeric,.01),coalesce((p_rule->>'minimum_order_amount')::numeric,0),nullif(p_rule->>'maximum_redeemable_points','')::bigint,coalesce((p_rule->>'priority')::int,100),coalesce((p_rule->>'is_active')::boolean,true))on conflict(id)do update set name=excluded.name,rule_type=excluded.rule_type,points_per_try=excluded.points_per_try,bonus_points=excluded.bonus_points,redemption_value_per_point=excluded.redemption_value_per_point,minimum_order_amount=excluded.minimum_order_amount,maximum_redeemable_points=excluded.maximum_redeemable_points,priority=excluded.priority,is_active=excluded.is_active,updated_at=now()returning id into v_id;perform public.write_audit_log('reward_rule_updated','settings',v_id::text,p_rule->>'name',null,p_rule,'{}');return v_id;end$$;
alter function public.create_order(jsonb) rename to create_order_without_loyalty;
create or replace function public.create_order(p_payload jsonb)returns jsonb language plpgsql security definer set search_path='' as $$declare v_result jsonb;v_points bigint:=coalesce((p_payload->>'loyalty_points')::bigint,0);v_discount numeric:=0;v_order uuid;begin v_result:=public.create_order_without_loyalty(p_payload-'loyalty_points');v_order:=(v_result->>'id')::uuid;if v_points>0 then v_discount:=public.redeem_loyalty_points(v_points,v_order);select jsonb_build_object('id',o.id,'order_number',o.order_number,'grand_total',o.grand_total,'created_at',o.created_at,'subtotal',o.subtotal,'discount_total',o.discount_total,'campaign_discount',coalesce((select sum((campaign->>'amount')::numeric)from jsonb_array_elements(o.campaign_snapshots)campaign),0),'coupon_discount',o.coupon_discount_amount,'loyalty_discount',o.loyalty_discount,'loyalty_points_redeemed',o.loyalty_points_redeemed)into v_result from public.orders o where o.id=v_order;end if;return v_result;end$$;
create or replace function public.loyalty_order_status_trigger()returns trigger language plpgsql security definer set search_path='' as $$begin if new.status='delivered'and old.status is distinct from'delivered'and new.user_id is not null then perform public.earn_loyalty_points(new.user_id,new.id,null,'Teslim edilen sipariş');elsif new.status='cancelled'and old.status is distinct from'cancelled'then perform public.refund_loyalty_points(new.id);end if;return new;end$$;drop trigger if exists loyalty_order_status on public.orders;create trigger loyalty_order_status after update of status on public.orders for each row execute function public.loyalty_order_status_trigger();
revoke all on function public.ensure_loyalty_account(uuid),public.earn_loyalty_points(uuid,uuid,bigint,text),public.redeem_loyalty_points(bigint,uuid),public.refund_loyalty_points(uuid),public.adjust_loyalty_points(uuid,bigint,text),public.admin_save_reward_rule(jsonb)from public,anon;grant execute on function public.redeem_loyalty_points(bigint,uuid)to authenticated;grant execute on function public.adjust_loyalty_points(uuid,bigint,text),public.admin_save_reward_rule(jsonb)to authenticated;grant execute on function public.create_order(jsonb)to anon,authenticated;
-- Final idempotent earning implementation; repeated delivery events cannot credit twice.
create or replace function public.earn_loyalty_points(p_user_id uuid,p_order_id uuid,p_points bigint default null,p_reason text default 'Order reward')returns bigint language plpgsql security definer set search_path='' as $$
declare v_account uuid;v_points bigint;v_balance bigint;v_total numeric;v_bonus bigint:=0;
begin
 if not public.current_user_is_admin()and auth.uid()<>p_user_id then raise exception'forbidden';end if;
 if exists(select 1 from public.loyalty_transactions where idempotency_key='earn:'||p_order_id)then return 0;end if;
 select grand_total into v_total from public.orders where id=p_order_id and user_id=p_user_id for update;if not found then raise exception'order_not_found';end if;
 select coalesce(p_points,floor(v_total*r.points_per_try)::bigint)into v_points from public.reward_rules r where r.rule_type='purchase'and r.is_active and v_total>=r.minimum_order_amount and(r.starts_at is null or r.starts_at<=now())and(r.ends_at is null or r.ends_at>=now())order by r.priority limit 1;
 if not exists(select 1 from public.orders where user_id=p_user_id and id<>p_order_id and status='delivered')then select coalesce(max(bonus_points),0)into v_bonus from public.reward_rules where rule_type='first_order'and is_active;end if;
 v_bonus:=v_bonus+coalesce((select sum(r.bonus_points)from public.reward_rules r where r.is_active and r.rule_type in('category','brand','campaign')and(r.starts_at is null or r.starts_at<=now())and(r.ends_at is null or r.ends_at>=now())and((r.rule_type='category'and exists(select 1 from public.order_items oi join public.products p on p.id=oi.product_id where oi.order_id=p_order_id and p.category_id=r.category_id))or(r.rule_type='brand'and exists(select 1 from public.order_items oi join public.products p on p.id=oi.product_id where oi.order_id=p_order_id and p.brand_id=r.brand_id))or(r.rule_type='campaign'and exists(select 1 from public.orders o where o.id=p_order_id and o.campaign_snapshots @> jsonb_build_array(jsonb_build_object('id',r.campaign_id::text))))),0);
 v_points:=coalesce(v_points,0)+v_bonus;if v_points<=0 then return 0;end if;
 v_account:=public.ensure_loyalty_account(p_user_id);update public.loyalty_accounts set available_points=available_points+v_points,lifetime_earned=lifetime_earned+v_points,updated_at=now()where id=v_account returning available_points into v_balance;
 insert into public.loyalty_transactions(account_id,user_id,order_id,type,points,balance_after,description,idempotency_key,metadata)values(v_account,p_user_id,p_order_id,case when v_bonus>0 then'bonus'else'earn'end,v_points,v_balance,p_reason,'earn:'||p_order_id,jsonb_build_object('first_order_bonus',v_bonus));
 update public.orders set loyalty_points_earned=v_points,loyalty_snapshot=loyalty_snapshot||jsonb_build_object('earned',v_points,'first_order_bonus',v_bonus)where id=p_order_id;
 perform public.publish_notification_event(case when v_bonus>0 then'bonus_received'else'points_earned'end,'order',p_order_id::text,jsonb_build_object('user_id',p_user_id,'points',v_points));
 insert into public.analytics_events(event_name,entity_type,entity_id,user_id,payload)values('points_earned','order',p_order_id::text,p_user_id,jsonb_build_object('points',v_points));
 insert into public.customer_activity(customer_id,activity_type,description,metadata)select id,'loyalty_points_earned','Loyalty points earned',jsonb_build_object('points',v_points,'order_id',p_order_id)from public.customer_profiles where user_id=p_user_id;
 return v_points;
end$$;
-- Extra insertion guard protects all future idempotent transaction writers.
create or replace function public.guard_loyalty_earn_duplicate()returns trigger language plpgsql set search_path='' as $$begin if new.idempotency_key is not null and exists(select 1 from public.loyalty_transactions where idempotency_key=new.idempotency_key)then return null;end if;return new;end$$;
drop trigger if exists loyalty_transaction_duplicate_guard on public.loyalty_transactions;
create trigger loyalty_transaction_duplicate_guard before insert on public.loyalty_transactions for each row execute function public.guard_loyalty_earn_duplicate();
insert into public.loyalty_accounts(user_id)select id from public.profiles on conflict(user_id)do nothing;
create or replace function public.create_loyalty_account_for_profile()returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.loyalty_accounts(user_id)values(new.id)on conflict(user_id)do nothing;return new;end$$;
drop trigger if exists profile_loyalty_account on public.profiles;
create trigger profile_loyalty_account after insert on public.profiles for each row execute function public.create_loyalty_account_for_profile();
create or replace function public.refund_loyalty_points(p_order_id uuid)returns boolean language plpgsql security definer set search_path='' as $$
declare v_r public.reward_redemptions%rowtype;v_account public.loyalty_accounts%rowtype;v_user uuid;v_earned bigint;v_reverse bigint;v_balance bigint;
begin
 if not public.current_user_is_admin()then raise exception'forbidden';end if;
 select user_id,loyalty_points_earned into v_user,v_earned from public.orders where id=p_order_id for update;if not found then raise exception'order_not_found';end if;
 select*into v_r from public.reward_redemptions where order_id=p_order_id and status='redeemed'for update;
 if found then update public.loyalty_accounts set available_points=available_points+v_r.points,lifetime_redeemed=greatest(0,lifetime_redeemed-v_r.points),updated_at=now()where id=v_r.account_id returning available_points into v_balance;update public.reward_redemptions set status='refunded',updated_at=now()where id=v_r.id;insert into public.loyalty_transactions(account_id,user_id,order_id,type,points,balance_after,description,idempotency_key)values(v_r.account_id,v_r.user_id,p_order_id,'refund',v_r.points,v_balance,'Redeemed points restored','refund:'||p_order_id)on conflict do nothing;end if;
 if v_user is not null and coalesce(v_earned,0)>0 and not exists(select 1 from public.loyalty_transactions where idempotency_key='earn-reversal:'||p_order_id)then select*into v_account from public.loyalty_accounts where user_id=v_user for update;v_reverse:=least(v_account.available_points,v_earned);if v_reverse>0 then update public.loyalty_accounts set available_points=available_points-v_reverse,lifetime_earned=greatest(0,lifetime_earned-v_reverse),updated_at=now()where id=v_account.id returning available_points into v_balance;insert into public.loyalty_transactions(account_id,user_id,order_id,type,points,balance_after,description,idempotency_key)values(v_account.id,v_user,p_order_id,'refund',-v_reverse,v_balance,'Earned points reversed','earn-reversal:'||p_order_id);end if;end if;
 perform public.write_audit_log('loyalty_points_refunded','order',p_order_id::text,'Loyalty refund',null,jsonb_build_object('earned_reversed',coalesce(v_reverse,0)),'{}');return true;
end$$;
create or replace function public.loyalty_order_status_trigger()returns trigger language plpgsql security definer set search_path='' as $$begin if new.status='delivered'and old.status is distinct from'delivered'and new.user_id is not null then perform public.earn_loyalty_points(new.user_id,new.id,null,'Delivered order');elsif(new.status='cancelled'and old.status is distinct from'cancelled')or(new.payment_status='refunded'and old.payment_status is distinct from'refunded')or(new.fulfillment_status='returned'and old.fulfillment_status is distinct from'returned')then perform public.refund_loyalty_points(new.id);end if;return new;end$$;
drop trigger if exists loyalty_order_status on public.orders;
create trigger loyalty_order_status after update of status,payment_status,fulfillment_status on public.orders for each row execute function public.loyalty_order_status_trigger();
commit;
