begin;

create table if not exists public.live_chat_video_settings (
  id boolean primary key default true check (id),
  enabled boolean not null default false,
  avatar_mode text not null default 'audio-reactive'
    check (avatar_mode in ('static', 'audio-reactive')),
  avatar_display_name text not null default 'CENTER GSM Dijital Temsilci'
    check (char_length(btrim(avatar_display_name)) between 2 and 80),
  avatar_image_url text,
  avatar_image_path text,
  ring_timeout_seconds integer not null default 45
    check (ring_timeout_seconds between 15 and 120),
  max_duration_seconds integer not null default 1200
    check (max_duration_seconds between 60 and 3600),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

insert into public.live_chat_video_settings (id)
values (true)
on conflict (id) do nothing;

create table if not exists public.live_chat_calls (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.live_chat_conversations(id) on delete cascade,
  status text not null default 'ringing'
    check (status in (
      'requesting', 'ringing', 'accepted', 'connecting', 'connected',
      'reconnecting', 'ended', 'rejected', 'missed', 'failed'
    )),
  accepted_by uuid references auth.users(id) on delete set null,
  signaling_nonce uuid not null default gen_random_uuid(),
  revision integer not null default 1 check (revision > 0),
  requested_at timestamptz not null default now(),
  accepted_at timestamptz,
  connecting_at timestamptz,
  connected_at timestamptz,
  ended_at timestamptz,
  expires_at timestamptz not null,
  auth_expires_at timestamptz not null,
  duration_seconds integer,
  ended_by text check (ended_by is null or ended_by in ('customer', 'admin', 'system')),
  end_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.live_chat_call_events (
  id bigint generated by default as identity primary key,
  call_id uuid not null references public.live_chat_calls(id) on delete cascade,
  conversation_id uuid not null references public.live_chat_conversations(id) on delete cascade,
  event_type text not null
    check (event_type in (
      'requested', 'accepted', 'connecting', 'started', 'reconnecting',
      'ended', 'rejected', 'missed', 'failed'
    )),
  actor_role text not null check (actor_role in ('customer', 'admin', 'system')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.live_chat_call_rate_limits (
  key_hash text not null,
  window_started_at timestamptz not null,
  request_count integer not null default 1 check (request_count > 0),
  updated_at timestamptz not null default now(),
  primary key (key_hash, window_started_at)
);

create index if not exists live_chat_calls_conversation_created_idx
  on public.live_chat_calls (conversation_id, created_at desc);
create index if not exists live_chat_calls_status_expires_idx
  on public.live_chat_calls (status, expires_at);
create index if not exists live_chat_call_events_conversation_created_idx
  on public.live_chat_call_events (conversation_id, created_at);
create index if not exists live_chat_call_rate_limits_updated_idx
  on public.live_chat_call_rate_limits (updated_at);

create unique index if not exists live_chat_calls_one_active_conversation_idx
  on public.live_chat_calls (conversation_id)
  where status in ('requesting', 'ringing', 'accepted', 'connecting', 'connected', 'reconnecting');

create unique index if not exists live_chat_calls_one_active_admin_idx
  on public.live_chat_calls (accepted_by)
  where accepted_by is not null
    and status in ('accepted', 'connecting', 'connected', 'reconnecting');

alter table public.live_chat_video_settings enable row level security;
alter table public.live_chat_calls enable row level security;
alter table public.live_chat_call_events enable row level security;
alter table public.live_chat_call_rate_limits enable row level security;

drop policy if exists "Admins manage live chat video settings" on public.live_chat_video_settings;
create policy "Admins manage live chat video settings"
on public.live_chat_video_settings for all to authenticated
using ((select public.current_user_is_admin()))
with check ((select public.current_user_is_admin()));

drop policy if exists "Visitors read own live chat calls" on public.live_chat_calls;
create policy "Visitors read own live chat calls"
on public.live_chat_calls for select to anon
using (
  exists (
    select 1
    from public.live_chat_conversations conversation
    where conversation.id = live_chat_calls.conversation_id
      and conversation.visitor_token = public.live_chat_request_token()
  )
);

drop policy if exists "Call participants read authorized live chat call" on public.live_chat_calls;
create policy "Call participants read authorized live chat call"
on public.live_chat_calls for select to authenticated
using (
  (select public.current_user_is_admin())
  or (
    id::text = coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'call_id', '')
    and signaling_nonce::text = coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'call_nonce', '')
    and auth_expires_at > now()
  )
);

drop policy if exists "Visitors read own live chat call events" on public.live_chat_call_events;
create policy "Visitors read own live chat call events"
on public.live_chat_call_events for select to anon
using (
  exists (
    select 1
    from public.live_chat_conversations conversation
    where conversation.id = live_chat_call_events.conversation_id
      and conversation.visitor_token = public.live_chat_request_token()
  )
);

drop policy if exists "Call participants read authorized live chat call events" on public.live_chat_call_events;
create policy "Call participants read authorized live chat call events"
on public.live_chat_call_events for select to authenticated
using (
  (select public.current_user_is_admin())
  or exists (
    select 1
    from public.live_chat_calls call
    where call.id = live_chat_call_events.call_id
      and call.id::text = coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'call_id', '')
      and call.signaling_nonce::text = coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'call_nonce', '')
      and call.auth_expires_at > now()
  )
);

revoke all on public.live_chat_video_settings from public, anon, authenticated;
revoke all on public.live_chat_calls from public, anon, authenticated;
revoke all on public.live_chat_call_events from public, anon, authenticated;
revoke all on public.live_chat_call_rate_limits from public, anon, authenticated;
grant select, update on public.live_chat_video_settings to authenticated;
grant select on public.live_chat_calls to anon, authenticated;
grant select on public.live_chat_call_events to anon, authenticated;

create or replace function public.expire_live_chat_calls()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_count integer := 0;
  v_abandoned integer := 0;
begin
  with expired as (
    update public.live_chat_calls
    set status = 'missed',
        ended_at = now(),
        ended_by = 'system',
        end_reason = 'ring_timeout',
        revision = revision + 1,
        updated_at = now()
    where status in ('requesting', 'ringing')
      and expires_at <= now()
    returning id, conversation_id
  ), logged as (
    insert into public.live_chat_call_events (
      call_id, conversation_id, event_type, actor_role, metadata
    )
    select id, conversation_id, 'missed', 'system', jsonb_build_object('reason', 'ring_timeout')
    from expired
    returning 1
  )
  select count(*) into v_count from logged;

  with abandoned as (
    update public.live_chat_calls
    set status = 'failed',
        ended_at = now(),
        ended_by = 'system',
        end_reason = 'authorization_expired',
        duration_seconds = case
          when connected_at is null then 0
          else greatest(0, floor(extract(epoch from (now() - connected_at)))::integer)
        end,
        revision = revision + 1,
        updated_at = now()
    where status in ('accepted', 'connecting', 'connected', 'reconnecting')
      and auth_expires_at <= now()
    returning id, conversation_id, duration_seconds
  ), logged as (
    insert into public.live_chat_call_events (
      call_id, conversation_id, event_type, actor_role, metadata
    )
    select id, conversation_id, 'failed', 'system', jsonb_build_object(
      'reason', 'authorization_expired',
      'durationSeconds', coalesce(duration_seconds, 0)
    )
    from abandoned
    returning 1
  )
  select count(*) into v_abandoned from logged;

  delete from public.live_chat_call_rate_limits
  where updated_at < now() - interval '1 day';

  return v_count + v_abandoned;
end;
$$;

create or replace function public.request_live_chat_call(
  p_conversation_id uuid,
  p_rate_key_hash text,
  p_limit integer,
  p_window_seconds integer,
  p_ring_timeout_seconds integer,
  p_max_duration_seconds integer
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_call public.live_chat_calls%rowtype;
  v_rate_count integer;
  v_window_started_at timestamptz;
begin
  if p_conversation_id is null
    or char_length(p_rate_key_hash) < 32
    or p_limit < 1 or p_limit > 20
    or p_window_seconds < 30 or p_window_seconds > 86400
    or p_ring_timeout_seconds < 15 or p_ring_timeout_seconds > 120
    or p_max_duration_seconds < 60 or p_max_duration_seconds > 3600 then
    return jsonb_build_object('ok', false, 'error', 'invalid_parameters');
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_conversation_id::text, 0));
  perform public.expire_live_chat_calls();

  if exists (
    select 1 from public.live_chat_calls
    where conversation_id = p_conversation_id
      and status in ('requesting', 'ringing', 'accepted', 'connecting', 'connected', 'reconnecting')
  ) then
    return jsonb_build_object('ok', false, 'error', 'active_call_exists');
  end if;

  v_window_started_at := to_timestamp(
    floor(extract(epoch from now()) / p_window_seconds) * p_window_seconds
  );

  insert into public.live_chat_call_rate_limits (
    key_hash, window_started_at, request_count, updated_at
  ) values (
    p_rate_key_hash, v_window_started_at, 1, now()
  )
  on conflict (key_hash, window_started_at) do update
    set request_count = public.live_chat_call_rate_limits.request_count + 1,
        updated_at = now()
    where public.live_chat_call_rate_limits.request_count < p_limit
  returning request_count into v_rate_count;

  if v_rate_count is null then
    return jsonb_build_object('ok', false, 'error', 'rate_limited');
  end if;

  insert into public.live_chat_calls (
    conversation_id, status, expires_at, auth_expires_at
  ) values (
    p_conversation_id,
    'ringing',
    now() + make_interval(secs => p_ring_timeout_seconds),
    now() + make_interval(secs => p_ring_timeout_seconds + p_max_duration_seconds + 300)
  )
  returning * into v_call;

  insert into public.live_chat_call_events (
    call_id, conversation_id, event_type, actor_role
  ) values (
    v_call.id, v_call.conversation_id, 'requested', 'customer'
  );

  return jsonb_build_object('ok', true, 'call', to_jsonb(v_call));
exception
  when unique_violation then
    return jsonb_build_object('ok', false, 'error', 'active_call_exists');
end;
$$;

create or replace function public.transition_live_chat_call(
  p_call_id uuid,
  p_expected_revision integer,
  p_action text,
  p_actor_role text,
  p_actor_id uuid default null,
  p_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_call public.live_chat_calls%rowtype;
  v_event_type text;
  v_duration integer;
begin
  if p_actor_role not in ('customer', 'admin', 'system') then
    return jsonb_build_object('ok', false, 'error', 'invalid_actor');
  end if;

  select * into v_call
  from public.live_chat_calls
  where id = p_call_id
  for update;

  if not found then
    return jsonb_build_object('ok', false, 'error', 'call_not_found');
  end if;

  if v_call.revision <> p_expected_revision then
    return jsonb_build_object('ok', false, 'error', 'stale_revision', 'call', to_jsonb(v_call));
  end if;

  if v_call.status in ('requesting', 'ringing') and v_call.expires_at <= now() then
    update public.live_chat_calls
    set status = 'missed', ended_at = now(), ended_by = 'system',
        end_reason = 'ring_timeout', revision = revision + 1, updated_at = now()
    where id = p_call_id
    returning * into v_call;
    insert into public.live_chat_call_events (
      call_id, conversation_id, event_type, actor_role, metadata
    ) values (
      v_call.id, v_call.conversation_id, 'missed', 'system', jsonb_build_object('reason', 'ring_timeout')
    );
    return jsonb_build_object('ok', false, 'error', 'call_expired', 'call', to_jsonb(v_call));
  end if;

  if p_action = 'accept' then
    if p_actor_role <> 'admin' or p_actor_id is null then
      return jsonb_build_object('ok', false, 'error', 'admin_required');
    end if;
    if v_call.status <> 'ringing' then
      return jsonb_build_object('ok', false, 'error', 'call_already_taken', 'call', to_jsonb(v_call));
    end if;
    if exists (
      select 1 from public.live_chat_calls
      where accepted_by = p_actor_id
        and id <> p_call_id
        and status in ('accepted', 'connecting', 'connected', 'reconnecting')
    ) then
      return jsonb_build_object('ok', false, 'error', 'admin_busy');
    end if;
    update public.live_chat_calls
    set status = 'accepted', accepted_by = p_actor_id, accepted_at = now(),
        revision = revision + 1, updated_at = now()
    where id = p_call_id and status = 'ringing'
    returning * into v_call;
    if not found then
      return jsonb_build_object('ok', false, 'error', 'call_already_taken');
    end if;
    v_event_type := 'accepted';
  elsif p_action = 'reject' then
    if p_actor_role <> 'admin' or v_call.status <> 'ringing' then
      return jsonb_build_object('ok', false, 'error', 'invalid_transition');
    end if;
    update public.live_chat_calls
    set status = 'rejected', ended_at = now(), ended_by = 'admin',
        end_reason = coalesce(nullif(p_reason, ''), 'rejected'),
        revision = revision + 1, updated_at = now()
    where id = p_call_id returning * into v_call;
    v_event_type := 'rejected';
  elsif p_action = 'connecting' then
    if v_call.status not in ('accepted', 'reconnecting') then
      return jsonb_build_object('ok', false, 'error', 'invalid_transition');
    end if;
    update public.live_chat_calls
    set status = 'connecting', connecting_at = coalesce(connecting_at, now()),
        revision = revision + 1, updated_at = now()
    where id = p_call_id returning * into v_call;
    v_event_type := 'connecting';
  elsif p_action = 'connected' then
    if v_call.status not in ('accepted', 'connecting', 'reconnecting', 'connected') then
      return jsonb_build_object('ok', false, 'error', 'invalid_transition');
    end if;
    if v_call.status = 'connected' then
      return jsonb_build_object('ok', true, 'call', to_jsonb(v_call));
    end if;
    update public.live_chat_calls
    set status = 'connected', connected_at = coalesce(connected_at, now()),
        revision = revision + 1, updated_at = now()
    where id = p_call_id returning * into v_call;
    v_event_type := 'started';
  elsif p_action = 'reconnecting' then
    if v_call.status not in ('connecting', 'connected') then
      return jsonb_build_object('ok', false, 'error', 'invalid_transition');
    end if;
    update public.live_chat_calls
    set status = 'reconnecting', revision = revision + 1, updated_at = now()
    where id = p_call_id returning * into v_call;
    v_event_type := 'reconnecting';
  elsif p_action in ('end', 'fail') then
    if v_call.status in ('ended', 'rejected', 'missed', 'failed') then
      return jsonb_build_object('ok', true, 'call', to_jsonb(v_call));
    end if;
    v_duration := case
      when v_call.connected_at is null then 0
      else greatest(0, floor(extract(epoch from (now() - v_call.connected_at)))::integer)
    end;
    update public.live_chat_calls
    set status = case when p_action = 'fail' then 'failed' else 'ended' end,
        ended_at = now(), ended_by = p_actor_role,
        end_reason = coalesce(nullif(p_reason, ''), p_action),
        duration_seconds = v_duration, revision = revision + 1, updated_at = now()
    where id = p_call_id returning * into v_call;
    v_event_type := case when p_action = 'fail' then 'failed' else 'ended' end;
  else
    return jsonb_build_object('ok', false, 'error', 'invalid_action');
  end if;

  insert into public.live_chat_call_events (
    call_id, conversation_id, event_type, actor_role, metadata
  ) values (
    v_call.id,
    v_call.conversation_id,
    v_event_type,
    p_actor_role,
    case
      when v_event_type in ('ended', 'failed') then jsonb_build_object(
        'reason', coalesce(nullif(p_reason, ''), p_action),
        'durationSeconds', coalesce(v_call.duration_seconds, 0)
      )
      else '{}'::jsonb
    end
  );

  return jsonb_build_object('ok', true, 'call', to_jsonb(v_call));
exception
  when unique_violation then
    return jsonb_build_object('ok', false, 'error', 'admin_busy');
end;
$$;

revoke all on function public.expire_live_chat_calls() from public, anon, authenticated;
revoke all on function public.request_live_chat_call(uuid, text, integer, integer, integer, integer) from public, anon, authenticated;
revoke all on function public.transition_live_chat_call(uuid, integer, text, text, uuid, text) from public, anon, authenticated;
grant execute on function public.expire_live_chat_calls() to service_role;
grant execute on function public.request_live_chat_call(uuid, text, integer, integer, integer, integer) to service_role;
grant execute on function public.transition_live_chat_call(uuid, integer, text, text, uuid, text) to service_role;

drop policy if exists "Live chat call participants receive private broadcasts" on realtime.messages;
create policy "Live chat call participants receive private broadcasts"
on realtime.messages for select to authenticated
using (
  realtime.messages.extension = 'broadcast'
  and exists (
    select 1
    from public.live_chat_calls call
    where (select realtime.topic()) = 'call:' || call.id::text
      and call.id::text = coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'call_id', '')
      and call.signaling_nonce::text = coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'call_nonce', '')
      and call.auth_expires_at > now()
      and call.status in ('ringing', 'accepted', 'connecting', 'connected', 'reconnecting')
  )
);

drop policy if exists "Live chat call participants send private broadcasts" on realtime.messages;
create policy "Live chat call participants send private broadcasts"
on realtime.messages for insert to authenticated
with check (
  realtime.messages.extension = 'broadcast'
  and exists (
    select 1
    from public.live_chat_calls call
    where (select realtime.topic()) = 'call:' || call.id::text
      and call.id::text = coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'call_id', '')
      and call.signaling_nonce::text = coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'call_nonce', '')
      and call.auth_expires_at > now()
      and call.status in ('ringing', 'accepted', 'connecting', 'connected', 'reconnecting')
  )
);

commit;
