create extension if not exists pgcrypto with schema extensions;
create table if not exists public.payment_providers(
 id uuid primary key default gen_random_uuid(),code text not null unique check(code in('mock','iyzico','paytr','param')),name text not null,is_active boolean not null default false,
 mode text not null default 'sandbox' check(mode in('sandbox','production')),health_status text not null default 'unknown' check(health_status in('unknown','healthy','degraded','down')),
 last_health_check_at timestamptz,last_connected_at timestamptz,capabilities jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now())
);
create table if not exists public.payment_provider_settings(
 id uuid primary key default gen_random_uuid(),provider_id uuid not null references public.payment_providers(id) on delete cascade,setting_key text not null,
 public_value jsonb,secret_hash text,secret_env_key text,created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now()),
 unique(provider_id,setting_key),check(secret_hash is null or public_value is null)
);
create table if not exists public.payment_webhooks(
 id uuid primary key default gen_random_uuid(),provider_id uuid not null references public.payment_providers(id) on delete restrict,external_event_id text not null,event_type text not null,
 status text not null default 'received' check(status in('received','processing','processed','failed','ignored')),signature_valid boolean not null,payload_hash text not null,
 payload_summary jsonb not null default '{}'::jsonb,retry_count integer not null default 0,last_error text,received_at timestamptz not null default timezone('utc',now()),processed_at timestamptz,
 created_at timestamptz not null default timezone('utc',now()),unique(provider_id,external_event_id)
);
create table if not exists public.payment_refunds(
 id uuid primary key default gen_random_uuid(),payment_transaction_id uuid not null references public.payment_transactions(id) on delete restrict,order_id uuid not null references public.orders(id) on delete restrict,
 provider_id uuid not null references public.payment_providers(id) on delete restrict,refund_type text not null check(refund_type in('full','partial')),amount numeric(14,2) not null check(amount>0),
 status text not null default 'pending' check(status in('pending','succeeded','failed','cancelled')),provider_reference text,reason text,metadata jsonb not null default '{}'::jsonb,
 requested_by uuid references auth.users(id) on delete set null,processed_at timestamptz,created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now())
);
create index if not exists payment_webhooks_status_idx on public.payment_webhooks(status,received_at desc);create index if not exists payment_webhooks_provider_idx on public.payment_webhooks(provider_id,received_at desc);
create index if not exists payment_refunds_order_idx on public.payment_refunds(order_id,created_at desc);create index if not exists payment_refunds_status_idx on public.payment_refunds(status,created_at desc);
alter table public.payment_providers enable row level security;alter table public.payment_provider_settings enable row level security;alter table public.payment_webhooks enable row level security;alter table public.payment_refunds enable row level security;
revoke all on public.payment_providers,public.payment_provider_settings,public.payment_webhooks,public.payment_refunds from anon,authenticated;
grant select on public.payment_providers,public.payment_provider_settings,public.payment_webhooks,public.payment_refunds to authenticated;
create policy "Admins read payment providers" on public.payment_providers for select to authenticated using(public.is_admin());create policy "Admins read provider settings" on public.payment_provider_settings for select to authenticated using(public.is_admin());create policy "Admins read payment webhooks" on public.payment_webhooks for select to authenticated using(public.is_admin());create policy "Admins read payment refunds" on public.payment_refunds for select to authenticated using(public.is_admin());

insert into public.payment_providers(code,name,is_active,mode,capabilities)values
('mock','Production Mock Provider',true,'sandbox','{"payment":true,"cancel":true,"refund":true,"webhook":true}'),
('iyzico','İyzico',false,'sandbox','{"payment":true,"cancel":true,"refund":true,"webhook":true}'),
('paytr','PayTR',false,'sandbox','{"payment":true,"refund":true,"webhook":true}'),
('param','Param',false,'sandbox','{"payment":true,"cancel":true,"refund":true,"webhook":true}') on conflict(code) do nothing;

create or replace function public.admin_update_payment_provider(p_provider_id uuid,p_is_active boolean,p_mode text)
returns boolean language plpgsql security definer set search_path='' as $$begin if not public.is_admin() then raise exception 'admin_required' using errcode='42501';end if;update public.payment_providers set is_active=p_is_active,mode=p_mode,updated_at=timezone('utc',now()) where id=p_provider_id;perform public.write_audit_log('payment_provider_updated','payment',p_provider_id::text,'Payment provider',null,jsonb_build_object('is_active',p_is_active,'mode',p_mode),'{}');return true;end$$;
create or replace function public.admin_set_payment_provider_secret(p_provider_id uuid,p_setting_key text,p_secret text,p_env_key text)
returns boolean language plpgsql security definer set search_path='' as $$begin if not public.is_admin() then raise exception 'admin_required' using errcode='42501';end if;if length(p_secret)<16 then raise exception 'weak_secret' using errcode='22023';end if;insert into public.payment_provider_settings(provider_id,setting_key,secret_hash,secret_env_key)values(p_provider_id,p_setting_key,extensions.crypt(p_secret,extensions.gen_salt('bf')),p_env_key)on conflict(provider_id,setting_key)do update set secret_hash=excluded.secret_hash,secret_env_key=excluded.secret_env_key,updated_at=timezone('utc',now());return true;end$$;
create or replace function public.record_payment_webhook(p_provider text,p_external_event_id text,p_event_type text,p_payload_hash text,p_payload_summary jsonb,p_provider_secret text)
returns uuid language plpgsql security definer set search_path='' as $$declare v_provider uuid;v_hash text;v_id uuid;begin select p.id,s.secret_hash into v_provider,v_hash from public.payment_providers p join public.payment_provider_settings s on s.provider_id=p.id and s.setting_key='webhook_secret' where p.code=p_provider and p.is_active;if v_provider is null or v_hash is null or extensions.crypt(p_provider_secret,v_hash)<>v_hash then raise exception 'webhook_auth_failed' using errcode='42501';end if;insert into public.payment_webhooks(provider_id,external_event_id,event_type,signature_valid,payload_hash,payload_summary,status,processed_at)values(v_provider,p_external_event_id,p_event_type,true,p_payload_hash,coalesce(p_payload_summary,'{}'),'processed',timezone('utc',now()))on conflict(provider_id,external_event_id)do update set retry_count=payment_webhooks.retry_count+1 returning id into v_id;insert into public.analytics_events(event_name,entity_type,entity_id,payload)values(case when p_event_type like '%refund%' then 'payment_refunded' when p_event_type like '%fail%' then 'payment_failed' else 'payment_verified' end,'payment_webhook',v_id::text,jsonb_build_object('provider',p_provider,'event_type',p_event_type))on conflict do nothing;insert into public.notification_events(event_type,entity_type,entity_id,payload,status,processed_at)values('payment_webhook_processed','payment',v_id::text,jsonb_build_object('provider',p_provider,'event_type',p_event_type),'processed',timezone('utc',now()));return v_id;end$$;
create or replace function public.admin_create_payment_refund(p_transaction_id uuid,p_provider_id uuid,p_amount numeric,p_reason text)
returns uuid language plpgsql security definer set search_path='' as $$declare v_tx public.payment_transactions%rowtype;v_id uuid;begin if not public.is_admin() then raise exception 'admin_required' using errcode='42501';end if;select*into v_tx from public.payment_transactions where id=p_transaction_id for update;if not found or p_amount<=0 or p_amount>v_tx.amount then raise exception 'invalid_refund' using errcode='22023';end if;insert into public.payment_refunds(payment_transaction_id,order_id,provider_id,refund_type,amount,reason,requested_by)values(v_tx.id,v_tx.order_id,p_provider_id,case when p_amount=v_tx.amount then'full'else'partial'end,p_amount,nullif(trim(p_reason),''),auth.uid())returning id into v_id;perform public.write_audit_log('payment_refund_requested','payment',v_id::text,'Refund',null,jsonb_build_object('amount',p_amount),jsonb_build_object('order_id',v_tx.order_id));return v_id;end$$;
revoke all on function public.admin_update_payment_provider(uuid,boolean,text),public.admin_set_payment_provider_secret(uuid,text,text,text),public.admin_create_payment_refund(uuid,uuid,numeric,text) from public,anon;grant execute on function public.admin_update_payment_provider(uuid,boolean,text),public.admin_set_payment_provider_secret(uuid,text,text,text),public.admin_create_payment_refund(uuid,uuid,numeric,text) to authenticated;
revoke all on function public.record_payment_webhook(text,text,text,text,jsonb,text) from public;grant execute on function public.record_payment_webhook(text,text,text,text,jsonb,text) to anon,authenticated;

create or replace function public.record_payment_gateway_event(p_event text,p_provider text,p_reference text,p_status text,p_metadata jsonb)
returns boolean language plpgsql security definer set search_path='' as $$begin if auth.uid() is null then raise exception 'authentication_required' using errcode='42501';end if;if p_event not in('payment_started','payment_verified','payment_failed','payment_refunded','payment_cancelled')then raise exception 'invalid_event' using errcode='22023';end if;insert into public.analytics_events(event_name,entity_type,entity_id,user_id,payload)values(p_event,'payment',p_reference,auth.uid(),jsonb_build_object('provider',p_provider,'status',p_status))on conflict do nothing;insert into public.notification_events(event_type,entity_type,entity_id,payload,status,processed_at)values(p_event,'payment',p_reference,jsonb_build_object('provider',p_provider,'status',p_status),'processed',timezone('utc',now()));if public.is_admin() then perform public.write_audit_log(p_event,'payment',p_reference,p_provider,null,null,coalesce(p_metadata,'{}'));end if;return true;end$$;
revoke all on function public.record_payment_gateway_event(text,text,text,text,jsonb) from public,anon;grant execute on function public.record_payment_gateway_event(text,text,text,text,jsonb) to authenticated;

drop trigger if exists audit_payment_providers_changes on public.payment_providers;create trigger audit_payment_providers_changes after insert or update or delete on public.payment_providers for each row execute function public.audit_row_change('payment','payment');
drop trigger if exists audit_payment_webhooks_changes on public.payment_webhooks;create trigger audit_payment_webhooks_changes after insert or update or delete on public.payment_webhooks for each row execute function public.audit_row_change('payment','payment');
drop trigger if exists audit_payment_refunds_changes on public.payment_refunds;create trigger audit_payment_refunds_changes after insert or update or delete on public.payment_refunds for each row execute function public.audit_row_change('payment','payment');
