begin;
create table if not exists public.gift_cards(id uuid primary key default gen_random_uuid(),code text not null unique,title text not null,initial_balance numeric(12,2) not null check(initial_balance>0),balance numeric(12,2) not null check(balance>=0),currency text not null default'TRY'check(currency='TRY'),owner_user_id uuid references auth.users(id)on delete set null,starts_at timestamptz,ends_at timestamptz,is_active boolean not null default true,is_single_use boolean not null default false,gift_note text,created_by uuid references auth.users(id)on delete set null,created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now()));
create table if not exists public.gift_card_transactions(id uuid primary key default gen_random_uuid(),gift_card_id uuid not null references public.gift_cards(id)on delete restrict,user_id uuid references auth.users(id)on delete set null,order_id uuid references public.orders(id)on delete set null,type text not null check(type in('issue','redeem','topup','refund','adjustment')),amount numeric(12,2)not null check(amount<>0),balance_after numeric(12,2)not null check(balance_after>=0),description text,idempotency_key text unique,created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now()));
create table if not exists public.store_credit_accounts(id uuid primary key default gen_random_uuid(),user_id uuid not null unique references auth.users(id)on delete cascade,balance numeric(12,2)not null default 0 check(balance>=0),currency text not null default'TRY'check(currency='TRY'),lifetime_added numeric(12,2)not null default 0 check(lifetime_added>=0),lifetime_spent numeric(12,2)not null default 0 check(lifetime_spent>=0),created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now()));
create table if not exists public.store_credit_transactions(id uuid primary key default gen_random_uuid(),account_id uuid not null references public.store_credit_accounts(id)on delete restrict,user_id uuid not null references auth.users(id)on delete restrict,order_id uuid references public.orders(id)on delete set null,return_request_id uuid references public.return_requests(id)on delete set null,type text not null check(type in('load','spend','refund','bonus','adjustment')),amount numeric(12,2)not null check(amount<>0),balance_after numeric(12,2)not null check(balance_after>=0),description text,metadata jsonb not null default'{}'::jsonb,idempotency_key text unique,created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now()));
alter table public.orders add column if not exists gift_card_amount numeric(12,2)not null default 0,add column if not exists store_credit_amount numeric(12,2)not null default 0,add column if not exists gift_card_snapshot jsonb not null default'{}'::jsonb,add column if not exists store_credit_snapshot jsonb not null default'{}'::jsonb;
create index if not exists gift_cards_active_dates_idx on public.gift_cards(is_active,starts_at,ends_at);create index if not exists gift_cards_owner_idx on public.gift_cards(owner_user_id);create index if not exists gift_card_transactions_card_created_idx on public.gift_card_transactions(gift_card_id,created_at desc);create index if not exists store_credit_transactions_user_created_idx on public.store_credit_transactions(user_id,created_at desc);create index if not exists store_credit_transactions_order_idx on public.store_credit_transactions(order_id);
alter table public.gift_cards enable row level security;alter table public.gift_card_transactions enable row level security;alter table public.store_credit_accounts enable row level security;alter table public.store_credit_transactions enable row level security;
create policy gift_cards_owner_admin_read on public.gift_cards for select using(owner_user_id=auth.uid()or public.current_user_is_admin());create policy gift_card_transactions_owner_admin_read on public.gift_card_transactions for select using(user_id=auth.uid()or exists(select 1 from public.gift_cards g where g.id=gift_card_id and g.owner_user_id=auth.uid())or public.current_user_is_admin());create policy store_credit_owner_admin_read on public.store_credit_accounts for select using(user_id=auth.uid()or public.current_user_is_admin());create policy store_credit_transactions_owner_admin_read on public.store_credit_transactions for select using(user_id=auth.uid()or public.current_user_is_admin());
revoke insert,update,delete on public.gift_cards,public.gift_card_transactions,public.store_credit_accounts,public.store_credit_transactions from anon,authenticated;
insert into public.store_credit_accounts(user_id)select id from public.profiles on conflict(user_id)do nothing;
create or replace function public.ensure_store_credit_account(p_user uuid)returns uuid language plpgsql security definer set search_path='' as $$
declare v_id uuid;begin insert into public.store_credit_accounts(user_id)values(p_user)on conflict(user_id)do update set updated_at=public.store_credit_accounts.updated_at returning id into v_id;return v_id;end;
$$;
create or replace function public.create_store_credit_for_profile()returns trigger language plpgsql security definer set search_path=''as $$
begin perform public.ensure_store_credit_account(new.id);return new;end;
$$;drop trigger if exists profile_store_credit on public.profiles;create trigger profile_store_credit after insert on public.profiles for each row execute function public.create_store_credit_for_profile();
create or replace function public.create_gift_card(p_payload jsonb)returns uuid language plpgsql security definer set search_path=''as $$
declare v_id uuid;v_code text;v_amount numeric;begin if not public.current_user_is_admin()then raise exception'forbidden';end if;v_amount:=(p_payload->>'balance')::numeric;if v_amount<=0 then raise exception'invalid_amount';end if;v_code:=upper(coalesce(nullif(trim(p_payload->>'code'),''),'CG-'||encode(gen_random_bytes(12),'hex')));insert into public.gift_cards(code,title,initial_balance,balance,currency,owner_user_id,starts_at,ends_at,is_active,is_single_use,gift_note,created_by)values(v_code,p_payload->>'title',v_amount,v_amount,coalesce(p_payload->>'currency','TRY'),nullif(p_payload->>'owner_user_id','')::uuid,nullif(p_payload->>'starts_at','')::timestamptz,nullif(p_payload->>'ends_at','')::timestamptz,coalesce((p_payload->>'is_active')::boolean,true),coalesce((p_payload->>'is_single_use')::boolean,false),p_payload->>'gift_note',auth.uid())returning id into v_id;insert into public.gift_card_transactions(gift_card_id,user_id,type,amount,balance_after,description,idempotency_key)values(v_id,nullif(p_payload->>'owner_user_id','')::uuid,'issue',v_amount,v_amount,'Gift card issued','issue:'||v_id);perform public.write_audit_log('gift_card_created','payment',v_id::text,v_code,null,jsonb_build_object('amount',v_amount),'{}');perform public.publish_notification_event('gift_card_created','gift_card',v_id::text,jsonb_build_object('user_id',p_payload->>'owner_user_id','title',p_payload->>'title'));return v_id;end;
$$;
create or replace function public.validate_gift_card(p_code text)returns jsonb language plpgsql security definer set search_path=''as $$
declare g public.gift_cards%rowtype;begin select*into g from public.gift_cards where code=upper(trim(p_code))and is_active and balance>0 and(starts_at is null or starts_at<=now())and(ends_at is null or ends_at>=now());if not found then return jsonb_build_object('valid',false);end if;return jsonb_build_object('valid',true,'title',g.title,'balance',g.balance,'currency',g.currency);end;
$$;
create or replace function public.redeem_gift_card(p_code text,p_order_id uuid,p_amount numeric default null)returns numeric language plpgsql security definer set search_path=''as $$
declare g public.gift_cards%rowtype;v_order numeric;v_amount numeric;v_balance numeric;begin select*into g from public.gift_cards where code=upper(trim(p_code))for update;if not found or not g.is_active or g.balance<=0 or(g.starts_at is not null and g.starts_at>now())or(g.ends_at is not null and g.ends_at<now())then raise exception'invalid_gift_card';end if;if exists(select 1 from public.gift_card_transactions where idempotency_key='redeem:'||p_order_id)then return 0;end if;select grand_total into v_order from public.orders where id=p_order_id for update;if not found then raise exception'order_not_found';end if;v_amount:=least(g.balance,v_order,coalesce(p_amount,g.balance));if v_amount<=0 then return 0;end if;update public.gift_cards set balance=balance-v_amount,is_active=case when is_single_use or balance-v_amount=0 then false else is_active end,updated_at=now()where id=g.id returning balance into v_balance;insert into public.gift_card_transactions(gift_card_id,user_id,order_id,type,amount,balance_after,description,idempotency_key)values(g.id,auth.uid(),p_order_id,'redeem',-v_amount,v_balance,'Order redemption','redeem:'||p_order_id);update public.orders set gift_card_amount=v_amount,grand_total=greatest(0,grand_total-v_amount),gift_card_snapshot=jsonb_build_object('gift_card_id',g.id,'code_suffix',right(g.code,4),'title',g.title,'amount',v_amount,'currency',g.currency)where id=p_order_id;insert into public.analytics_events(event_name,entity_type,entity_id,user_id,payload)values('gift_card_redeemed','order',p_order_id::text,auth.uid(),jsonb_build_object('amount',v_amount));perform public.publish_notification_event('gift_card_used','order',p_order_id::text,jsonb_build_object('user_id',auth.uid(),'amount',v_amount));perform public.write_audit_log('gift_card_used','payment',g.id::text,g.title,null,jsonb_build_object('amount',v_amount),jsonb_build_object('order_id',p_order_id));return v_amount;end;
$$;
create or replace function public.add_store_credit(p_user_id uuid,p_amount numeric,p_reason text,p_order_id uuid default null,p_return_id uuid default null)returns numeric language plpgsql security definer set search_path=''as $$
declare v_id uuid;v_balance numeric;begin if not public.current_user_is_admin()or p_amount<=0 then raise exception'forbidden';end if;v_id:=public.ensure_store_credit_account(p_user_id);update public.store_credit_accounts set balance=balance+p_amount,lifetime_added=lifetime_added+p_amount,updated_at=now()where id=v_id returning balance into v_balance;insert into public.store_credit_transactions(account_id,user_id,order_id,return_request_id,type,amount,balance_after,description)values(v_id,p_user_id,p_order_id,p_return_id,'load',p_amount,v_balance,p_reason);perform public.publish_notification_event('store_credit_added','user',p_user_id::text,jsonb_build_object('user_id',p_user_id,'amount',p_amount));perform public.write_audit_log('store_credit_added','payment',v_id::text,'Store credit',null,jsonb_build_object('amount',p_amount,'balance',v_balance),jsonb_build_object('reason',p_reason));return v_balance;end;
$$;
create or replace function public.spend_store_credit(p_amount numeric,p_order_id uuid)returns numeric language plpgsql security definer set search_path=''as $$
declare v_user uuid:=auth.uid();a public.store_credit_accounts%rowtype;v_order numeric;v_amount numeric;begin if v_user is null or p_amount<=0 then raise exception'invalid_amount';end if;if exists(select 1 from public.store_credit_transactions where idempotency_key='spend:'||p_order_id)then return 0;end if;select*into a from public.store_credit_accounts where user_id=v_user for update;if not found or a.balance<=0 then raise exception'insufficient_credit';end if;select grand_total into v_order from public.orders where id=p_order_id and user_id=v_user for update;if not found then raise exception'order_not_found';end if;v_amount:=least(p_amount,a.balance,v_order);update public.store_credit_accounts set balance=balance-v_amount,lifetime_spent=lifetime_spent+v_amount,updated_at=now()where id=a.id;insert into public.store_credit_transactions(account_id,user_id,order_id,type,amount,balance_after,description,idempotency_key)values(a.id,v_user,p_order_id,'spend',-v_amount,a.balance-v_amount,'Order spend','spend:'||p_order_id);update public.orders set store_credit_amount=v_amount,grand_total=greatest(0,grand_total-v_amount),store_credit_snapshot=jsonb_build_object('account_id',a.id,'amount',v_amount,'currency',a.currency)where id=p_order_id;insert into public.analytics_events(event_name,entity_type,entity_id,user_id,payload)values('store_credit_spent','order',p_order_id::text,v_user,jsonb_build_object('amount',v_amount));insert into public.customer_activity(customer_id,activity_type,description,metadata)select id,'store_credit_used','Store credit used',jsonb_build_object('amount',v_amount,'order_id',p_order_id)from public.customer_profiles where user_id=v_user;return v_amount;end;
$$;
create or replace function public.refund_store_credit(p_order_id uuid,p_amount numeric,p_reason text default'Refund to store credit',p_return_id uuid default null)returns numeric language plpgsql security definer set search_path=''as $$
declare v_user uuid;v_id uuid;v_balance numeric;v_total numeric;begin if not public.current_user_is_admin()then raise exception'forbidden';end if;select user_id,grand_total+gift_card_amount+store_credit_amount into v_user,v_total from public.orders where id=p_order_id for update;if v_user is null or p_amount<=0 or p_amount>v_total then raise exception'invalid_refund';end if;v_id:=public.ensure_store_credit_account(v_user);if exists(select 1 from public.store_credit_transactions where idempotency_key='refund:'||p_order_id||':'||coalesce(p_return_id::text,'order'))then raise exception'already_refunded';end if;update public.store_credit_accounts set balance=balance+p_amount,lifetime_added=lifetime_added+p_amount,updated_at=now()where id=v_id returning balance into v_balance;insert into public.store_credit_transactions(account_id,user_id,order_id,return_request_id,type,amount,balance_after,description,idempotency_key)values(v_id,v_user,p_order_id,p_return_id,'refund',p_amount,v_balance,p_reason,'refund:'||p_order_id||':'||coalesce(p_return_id::text,'order'));insert into public.analytics_events(event_name,entity_type,entity_id,user_id,payload)values('refund_to_store_credit','order',p_order_id::text,v_user,jsonb_build_object('amount',p_amount));perform public.publish_notification_event('store_credit_added','order',p_order_id::text,jsonb_build_object('user_id',v_user,'amount',p_amount,'reason','refund'));perform public.write_audit_log('refund_to_store_credit','payment',v_id::text,'Store credit refund',null,jsonb_build_object('amount',p_amount),jsonb_build_object('order_id',p_order_id,'return_id',p_return_id));return v_balance;end;
$$;
create or replace function public.admin_update_gift_card(p_card_id uuid,p_action text,p_amount numeric default 0)returns boolean language plpgsql security definer set search_path=''as $$
declare v_balance numeric;begin if not public.current_user_is_admin()then raise exception'forbidden';end if;if p_action='deactivate'then update public.gift_cards set is_active=false,updated_at=now()where id=p_card_id;elsif p_action='topup'and p_amount>0 then update public.gift_cards set balance=balance+p_amount,initial_balance=initial_balance+p_amount,updated_at=now()where id=p_card_id returning balance into v_balance;insert into public.gift_card_transactions(gift_card_id,user_id,type,amount,balance_after,description)values(p_card_id,auth.uid(),'topup',p_amount,v_balance,'Admin topup');else raise exception'invalid_action';end if;perform public.write_audit_log('gift_card_updated','payment',p_card_id::text,'Gift card',null,jsonb_build_object('action',p_action,'amount',p_amount),'{}');return found;end;
$$;
alter function public.create_order(jsonb)rename to create_order_without_credit;
create or replace function public.create_order(p_payload jsonb)returns jsonb language plpgsql security definer set search_path=''as $$
declare r jsonb;v_id uuid;v_gift numeric:=0;v_credit numeric:=0;begin r:=public.create_order_without_credit(p_payload-'gift_card_code'-'gift_card_amount'-'store_credit_amount');v_id:=(r->>'id')::uuid;if nullif(trim(p_payload->>'gift_card_code'),'')is not null then v_gift:=public.redeem_gift_card(p_payload->>'gift_card_code',v_id,nullif(p_payload->>'gift_card_amount','')::numeric);end if;if coalesce((p_payload->>'store_credit_amount')::numeric,0)>0 then v_credit:=public.spend_store_credit((p_payload->>'store_credit_amount')::numeric,v_id);end if;select jsonb_build_object('id',o.id,'order_number',o.order_number,'grand_total',o.grand_total,'created_at',o.created_at,'subtotal',o.subtotal,'discount_total',o.discount_total,'campaign_discount',coalesce((select sum((campaign->>'amount')::numeric)from jsonb_array_elements(o.campaign_snapshots)campaign),0),'coupon_discount',o.coupon_discount_amount,'loyalty_discount',o.loyalty_discount,'loyalty_points_redeemed',o.loyalty_points_redeemed,'gift_card_amount',o.gift_card_amount,'store_credit_amount',o.store_credit_amount)into r from public.orders o where o.id=v_id;return r;end;
$$;
revoke all on function public.ensure_store_credit_account(uuid),public.create_gift_card(jsonb),public.redeem_gift_card(text,uuid,numeric),public.add_store_credit(uuid,numeric,text,uuid,uuid),public.spend_store_credit(numeric,uuid),public.refund_store_credit(uuid,numeric,text,uuid),public.admin_update_gift_card(uuid,text,numeric)from public,anon;grant execute on function public.validate_gift_card(text)to anon,authenticated;grant execute on function public.create_gift_card(jsonb),public.add_store_credit(uuid,numeric,text,uuid,uuid),public.refund_store_credit(uuid,numeric,text,uuid),public.admin_update_gift_card(uuid,text,numeric)to authenticated;grant execute on function public.create_order(jsonb)to anon,authenticated;
create or replace function public.credit_crm_event_trigger()returns trigger language plpgsql security definer set search_path=''as $$
declare v_type text;begin if tg_table_name='gift_card_transactions'then v_type:=case when new.type='issue'then'gift_card_created'when new.type='redeem'then'gift_card_used'else null end;else v_type:=case when new.type in('load','refund','bonus')then'store_credit_added'when new.type='spend'then'store_credit_used'else null end;end if;if v_type is not null and new.user_id is not null then insert into public.customer_activity(customer_id,activity_type,description,metadata)select id,v_type,v_type,jsonb_build_object('amount',new.amount,'transaction_id',new.id)from public.customer_profiles where user_id=new.user_id;end if;if tg_table_name='store_credit_transactions'and new.type='spend'then perform public.publish_notification_event('store_credit_used','order',coalesce(new.order_id::text,new.id::text),jsonb_build_object('user_id',new.user_id,'amount',abs(new.amount)));perform public.write_audit_log('store_credit_used','payment',new.account_id::text,'Store credit',null,jsonb_build_object('amount',abs(new.amount)),jsonb_build_object('order_id',new.order_id));end if;return new;end;
$$;
drop trigger if exists gift_card_crm_event on public.gift_card_transactions;create trigger gift_card_crm_event after insert on public.gift_card_transactions for each row execute function public.credit_crm_event_trigger();drop trigger if exists store_credit_crm_event on public.store_credit_transactions;create trigger store_credit_crm_event after insert on public.store_credit_transactions for each row execute function public.credit_crm_event_trigger();
commit;


