import { createClient } from "@/lib/supabase/client";
import type { AdminProductResult } from "@/types/admin-product";
import type { AdminInventoryMovement, AdminInventoryRow, InventoryFilters, MovementFilters, WarehouseValues } from "@/types/inventory";
import type { Tables } from "@/types/database";
const safe="Stok işlemi tamamlanamadı. Yetkinizi ve bağlantınızı kontrol edin.";const notConfigured="Supabase bağlantısı yapılandırılmamış.";
export async function getAdminWarehouses():Promise<AdminProductResult<Tables<"warehouses">[]>>{const c=createClient();if(!c)return{data:null,error:notConfigured};const r=await c.from("warehouses").select("*").order("is_default",{ascending:false}).order("name");return r.error?{data:null,error:safe}:{data:r.data,error:null};}
export async function createAdminWarehouse(v:WarehouseValues):Promise<AdminProductResult<Tables<"warehouses">>>{const c=createClient();if(!c)return{data:null,error:notConfigured};const d=v.is_default;const r=await c.from("warehouses").insert({...v,code:v.code.toUpperCase(),is_default:false}).select("*").single();if(r.error)return{data:null,error:r.error.code==="23505"?"Bu depo kodu kullanılıyor.":safe};if(d){const x=await setDefaultWarehouse(r.data.id);if(!x.data)return{data:null,error:x.error};}return{data:r.data,error:null};}
export async function updateAdminWarehouse(id:string,v:WarehouseValues):Promise<AdminProductResult<Tables<"warehouses">>>{const c=createClient();if(!c)return{data:null,error:notConfigured};const d=v.is_default;const r=await c.from("warehouses").update({...v,code:v.code.toUpperCase(),is_default:false}).eq("id",id).select("*").single();if(r.error)return{data:null,error:safe};if(d&&v.is_active){const x=await setDefaultWarehouse(id);if(!x.data)return{data:null,error:x.error};}return{data:r.data,error:null};}
export async function deactivateAdminWarehouse(id:string):Promise<AdminProductResult<true>>{const c=createClient();if(!c)return{data:null,error:notConfigured};const count=await c.from("inventory").select("id",{count:"exact",head:true}).eq("warehouse_id",id).gt("quantity_on_hand",0);if((count.count??0)>0)return{data:null,error:"Bu depoda stok bulunduğu için pasif yapılamaz."};const r=await c.from("warehouses").update({is_active:false,is_default:false}).eq("id",id);return r.error?{data:null,error:safe}:{data:true,error:null};}
export async function setDefaultWarehouse(id:string):Promise<AdminProductResult<true>>{const c=createClient();if(!c)return{data:null,error:notConfigured};const r=await c.rpc("set_default_warehouse",{p_warehouse_id:id});return r.error||!r.data?{data:null,error:safe}:{data:true,error:null};}
export async function getAdminInventory(filters:InventoryFilters={}):Promise<AdminProductResult<AdminInventoryRow[]>>{const c=createClient();if(!c)return{data:null,error:notConfigured};const [inventory,products,warehouses,images]=await Promise.all([c.from("inventory").select("*"),c.from("products").select("*"),c.from("warehouses").select("*"),c.from("product_images").select("*").eq("is_primary",true)]);if(inventory.error||products.error||warehouses.error||images.error)return{data:null,error:safe};const p=new Map(products.data.map(x=>[x.id,x]));const w=new Map(warehouses.data.map(x=>[x.id,x]));let rows=inventory.data.flatMap(i=>{const product=p.get(i.product_id),warehouse=w.get(i.warehouse_id);if(!product||!warehouse)return[];const available=i.quantity_on_hand-i.quantity_reserved;return[{...i,product,warehouse,image_url:images.data.find(x=>x.product_id===i.product_id)?.url??null,available_stock:available,status:available===0?"out-of-stock" as const:available<=i.reorder_level?"critical" as const:"in-stock" as const}];});const q=filters.query?.trim().toLocaleLowerCase("tr-TR");if(q)rows=rows.filter(x=>`${x.product.name} ${x.product.sku}`.toLocaleLowerCase("tr-TR").includes(q));if(filters.warehouseId)rows=rows.filter(x=>x.warehouse_id===filters.warehouseId);if(filters.productActive&&filters.productActive!=="all")rows=rows.filter(x=>x.product.is_active===(filters.productActive==="active"));if(filters.stock&&filters.stock!=="all")rows=rows.filter(x=>x.status===filters.stock);if(filters.sort==="stock-asc")rows.sort((a,b)=>a.available_stock-b.available_stock);else if(filters.sort==="stock-desc")rows.sort((a,b)=>b.available_stock-a.available_stock);else if(filters.sort==="critical")rows.sort((a,b)=>(a.available_stock-a.reorder_level)-(b.available_stock-b.reorder_level));else rows.sort((a,b)=>a.product.name.localeCompare(b.product.name,"tr"));return{data:rows,error:null};}
export async function adjustInventory(warehouseId:string,productId:string,movementType:"manual_increase"|"manual_decrease"|"stock_correction",quantity:number,note:string):Promise<AdminProductResult<true>>{const c=createClient();if(!c)return{data:null,error:notConfigured};const r=await c.rpc("adjust_inventory",{p_warehouse_id:warehouseId,p_product_id:productId,p_movement_type:movementType,p_quantity:quantity,p_note:note});return r.error||!r.data?{data:null,error:r.error?.message.includes("negative_available_stock")?"Negatif stok oluşturacak işlem yapılamaz.":safe}:{data:true,error:null};}
export async function updateReorderLevel(warehouseId:string,productId:string,level:number):Promise<AdminProductResult<true>>{const c=createClient();if(!c)return{data:null,error:notConfigured};const r=await c.rpc("set_inventory_reorder_level",{p_warehouse_id:warehouseId,p_product_id:productId,p_reorder_level:level});return r.error||!r.data?{data:null,error:safe}:{data:true,error:null};}
export async function getAdminInventoryMovements(filters:MovementFilters={}):Promise<AdminProductResult<AdminInventoryMovement[]>>{const c=createClient();if(!c)return{data:null,error:notConfigured};let q=c.from("inventory_movements").select("*").order("created_at",{ascending:false}).limit(500);if(filters.warehouseId)q=q.eq("warehouse_id",filters.warehouseId);if(filters.productId)q=q.eq("product_id",filters.productId);if(filters.movementType)q=q.eq("movement_type",filters.movementType);if(filters.dateFrom)q=q.gte("created_at",filters.dateFrom);if(filters.dateTo)q=q.lte("created_at",filters.dateTo);const [m,p,w,o]=await Promise.all([q,c.from("products").select("*"),c.from("warehouses").select("*"),c.from("orders").select("id,order_number")]);if(m.error||p.error||w.error||o.error)return{data:null,error:safe};const pm=new Map(p.data.map(x=>[x.id,x])),wm=new Map(w.data.map(x=>[x.id,x])),om=new Map(o.data.map(x=>[x.id,x.order_number]));let rows=m.data.map(x=>({...x,product_name:pm.get(x.product_id)?.name??"Silinmiş ürün",sku:pm.get(x.product_id)?.sku??"—",warehouse_name:wm.get(x.warehouse_id)?.name??"Silinmiş depo",order_number:x.order_id?om.get(x.order_id)??null:null,admin_name:x.created_by?"Yetkili admin":null}));if(filters.orderNumber)rows=rows.filter(x=>x.order_number?.toLocaleLowerCase("tr-TR").includes(filters.orderNumber!.toLocaleLowerCase("tr-TR")));return{data:rows,error:null};}
