import { createClient } from "@/lib/supabase/client";
import type { AdminProductResult } from "@/types/admin-product";
import type { Tables } from "@/types/database";
export type PaymentAccountValues = Pick<Tables<"payment_accounts">, "bank_name" | "account_holder" | "iban" | "branch" | "description" | "is_active" | "is_default">;
const safeError = "Banka hesabı işlemi tamamlanamadı. Yetkinizi ve bilgileri kontrol edin.";
export async function getAdminPaymentAccounts(): Promise<AdminProductResult<Tables<"payment_accounts">[]>> { const client=createClient(); if(!client)return{data:null,error:"Supabase bağlantısı yapılandırılmamış."}; const result=await client.from("payment_accounts").select("*").order("is_default",{ascending:false}).order("created_at"); return result.error?{data:null,error:safeError}:{data:result.data,error:null}; }
export async function createAdminPaymentAccount(values: PaymentAccountValues): Promise<AdminProductResult<Tables<"payment_accounts">>> { const client=createClient(); if(!client)return{data:null,error:"Supabase bağlantısı yapılandırılmamış."}; const makeDefault=values.is_default; const result=await client.from("payment_accounts").insert({...values,is_default:false,provider:"manual_bank_transfer"}).select("*").single(); if(result.error)return{data:null,error:result.error.code==="23505"?"Bu IBAN daha önce eklenmiş.":safeError}; if(makeDefault){const selected=await setDefaultPaymentAccount(result.data.id);if(!selected.data)return{data:null,error:selected.error};} return{data:result.data,error:null}; }
export async function updateAdminPaymentAccount(id:string,values:PaymentAccountValues):Promise<AdminProductResult<Tables<"payment_accounts">>>{const client=createClient();if(!client)return{data:null,error:"Supabase bağlantısı yapılandırılmamış."};const makeDefault=values.is_default;const result=await client.from("payment_accounts").update({...values,is_default:false}).eq("id",id).select("*").single();if(result.error)return{data:null,error:result.error.code==="23505"?"Bu IBAN daha önce eklenmiş.":safeError};if(makeDefault&&values.is_active){const selected=await setDefaultPaymentAccount(id);if(!selected.data)return{data:null,error:selected.error};}return{data:result.data,error:null};}
export async function deactivateAdminPaymentAccount(id:string):Promise<AdminProductResult<true>>{const client=createClient();if(!client)return{data:null,error:"Supabase bağlantısı yapılandırılmamış."};const result=await client.from("payment_accounts").update({is_active:false,is_default:false}).eq("id",id);return result.error?{data:null,error:safeError}:{data:true,error:null};}
export async function setDefaultPaymentAccount(id:string):Promise<AdminProductResult<true>>{const client=createClient();if(!client)return{data:null,error:"Supabase bağlantısı yapılandırılmamış."};const result=await client.rpc("admin_set_default_payment_account",{p_account_id:id});return result.error||!result.data?{data:null,error:safeError}:{data:true,error:null};}
